services:
  backend:
    build: .
    container_name: nestJs_app
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file: # ✅ Fix this line
      - .env
    volumes:
      - .:/app
      - /app/node_modules
  db:
    image: postgres
    restart: always
    container_name: postgres-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
